;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname B06b) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
(require picturing-programs)
#;(define (rq1 n)
  (max (min 1000 (+ n (* 100 n (+ 1 (random 9)))))))
#;(define (rq1 n)
  (max 100 (+ 100 (* 100 n (random)))))
(define (rq1 n)
  (+ 100 (* (random (+ 1 (quotient (- 1000 100) n))) n)))
(rq1 500)
(rq1 500)
(rq1 500)
(rq1 500)
(rq1 500)
(rq1 500)
(define (rects x)
  (rectangle (* x 1.618) x "outline" "black"))
(rects (+ 100 (random 201)))
(rects (+ 100 (random 201)))