;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname C15) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
(require picturing-programs)
(define-struct np (n p))
(define a (make-np 10 (make-posn 10 20)))
(define b (make-np 6 (make-posn 7 21)))
(check-expect (make-np 10 (make-posn 10 20)) a)
(check-expect (make-np 6 (make-posn 7 21)) b)
(define (np-set-num np n)
  (make-np n (np-p np)))
(check-expect (np-set-num a 20) (make-np 20 (make-posn 10 20)))
(define (np-set-posn np p)
  (make-np (np-n np) p))
(check-expect (np-set-posn b (make-posn 20 10)) (make-np 6 (make-posn 20 10)))

(define (dist x1 x2 y1 y2)
  (sqrt (+ (expt (- x2 x1) 2) (expt (- y2 y1) 2))))
(define (random-posn x y)
  (make-posn (random (+ x 1)) (random (+ y 1))))
(define (dh m)
  (place-image (circle 50 "solid" "blue") (posn-x (np-p m)) (posn-y (np-p m)) (empty-scene 400 300)))
(define (mh m x y e)
  (cond [(and (mouse=? e "button-down") (> 50 (dist (posn-x (np-p m)) x (posn-y (np-p m)) y))) (make-np (+ 1 (np-n m)) (make-posn 6969 6969))]
        [(mouse=? e "button-down") (make-np (+ 1 (np-n m)) (np-p m))]
        [else m]))
;; (define a (make-np 10 (make-posn 10 20)))
(check-expect (mh a 10 20 "button-down") (make-np 11 (make-posn 6969 6969)))
(check-expect (mh a 10 1350 "button-down") (make-np 11 (make-posn 10 20)))
(check-expect (mh a 10 50 "button-up") a)
(define (win? m)
  (cond [(= (posn-x (np-p m)) 6969) #true]
        [else #false]))
(define (win m)
  (place-image (text (number->string (np-n m)) 20 "blue") 200 175 (place-image (text "u won, took u this many tries:" 20 "blue") 200 125 (rectangle 400 300 "solid" "green"))))
(define (th m)
  (make-np (np-n m) (random-posn 400 300)))
#;(define (th m)
  (make-np (np-n m) (make-posn 100 100)))
(big-bang (make-np 0 (random-posn 400 300))
  (on-draw dh)
  (on-tick th 0.5)
  (on-mouse mh)
  (stop-when win? win))